-- DDL Exercise
CREATE DATABASE IF NOT EXISTS MovieCatalogue;

CREATE TABLE IF NOT EXISTS Genre(
GenreID INT PRIMARY KEY AUTO_INCREMENT,
GenreName VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Director(
DirectorID INT PRIMARY KEY AUTO_INCREMENT,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
BirthDate DATE
);

CREATE TABLE IF NOT EXISTS Rating(
RatingID INT PRIMARY KEY,
RatingName VARCHAR(5)
);

CREATE TABLE IF NOT EXISTS Actor(
ActorID INT PRIMARY KEY AUTO_INCREMENT,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
BirthDate DATE
);

CREATE TABLE IF NOT EXISTS Movie(
MovieID INT PRIMARY KEY AUTO_INCREMENT,
GenreID INT NOT NULL,
DirectorID INT NOT NULL,
RatingID INT NOT NULL,
FOREIGN KEY fk_Movie_Genre(GenreID)
	REFERENCES Genre(GenreID),
FOREIGN KEY fk_Movie_Director(DirectorID)
	REFERENCES Director(DirectorID),
FOREIGN KEY fk_Movie_Rating(RatingID)
	REFERENCES Rating(RatingID),
Title VARCHAR(128) NOT NULL,
ReleaseDate DATE
);

CREATE TABLE IF NOT EXISTS CastMembers(
CastMemberID INT PRIMARY KEY AUTO_INCREMENT,
ActorID INT NOT NULL,
MovieID INT NOT NULL,

FOREIGN KEY fk_CastMembers_Actor(ActorID)
	REFERENCES Actor(ActorID),
FOREIGN KEY fk_CastMembers_Movie(MovieID)
	REFERENCES Movie(MovieID),
Role VARCHAR(50) NOT NULL
);

